# Generated by Django 6.1.1 on 2026-09-18 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('image_url', models.URLField(blank=True, default='', max_length=150)),
                ('order', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
            ],
            options={
                'db_table': 'initiatives',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
            ],
            options={
                'db_table': 'statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_title', models.CharField(max_length=150)),
                ('vision_description', models.CharField(blank=True, default='', max_length=200)),
                ('mission_title', models.CharField(max_length=150)),
                ('mission_description', models.CharField(blank=True, default='', max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vision_mission',
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(default='home', max_length=50)),
                ('section', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('image', models.URLField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'page_content',
                'ordering': ['page_type', 'sort_order'],
            },
        ),
    ]
