# Generated by Django 6.1.1 on 2026-09-14 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(db_index=True, max_length=50)),
                ('section', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('image', models.URLField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'page_content',
                'ordering': ['page_type', 'sort_order'],
                'indexes': [models.Index(fields=['page_type', 'status'], name='page_conten_page_ty_fa3e6a_idx')],
            },
        ),
    ]
