# Generated by Django 6.1.1 on 2026-09-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('skills', models.TextField(blank=True, default='')),
                ('availability', models.CharField(blank=True, default='', max_length=50)),
                ('motivation', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'volunteers',
                'ordering': ['-applied_at'],
            },
        ),
    ]
