# Generated by Django 6.1.1 on 2026-09-15 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_phone', models.CharField(blank=True, default='', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('payment_payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('payment_signature', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, default='', max_length=20)),
                ('donor_message', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='projects.project')),
            ],
            options={
                'db_table': 'donations',
                'ordering': ['-date'],
            },
        ),
    ]
